#
# MAINTAINER: devops@onix-systems.com
#

version: "3"


services:

  server:
    hostname: server
    image: zabbix/zabbix-server-mysql:ubuntu-${ZBX_VERSION:-3.4}-latest
    ports:
      - "${ZBX_EXTERNAL_SERVER_PORT:-10051}:10051"
    networks:
      zabbix_net:
        ipv4_address: ${SUBNET_PREFIX:-172.15.0.}254
    links:
      - db
      - smtp:smtp.local
    extra_hosts:
      - "agent:${SUBNET_PREFIX:-172.15.0.}1"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  frontend:
    hostname: frontend
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-${ZBX_VERSION:-3.4}-latest
    ports:
      - "${HTTP_BIND_ADDR:-0.0.0.0:80}:80"
    networks:
      - zabbix_net
    links:
      - server
      - db
    environment:
      - ZBX_SERVER_HOST=server
      - DB_SERVER_HOST=db
      - PHP_TZ=${PHP_TZ:-Europe/Kiev}
      - ZBX_SERVER_NAME=${ZBX_SERVER_NAME:-zabbix}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    volumes:
      - ./configs/nginx.conf:/etc/zabbix/nginx.conf:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  db:
    hostname: db
    build:
      dockerfile: Dockerfile.database
      context: ./
    networks:
      - zabbix_net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  smtp:
    hostname: smtp
    image: tianon/exim4
    networks:
      - zabbix_net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  grafana:
    hostname: grafana
    build:
      dockerfile: Dockerfile.grafana
      context: ./
    restart: always
    networks:
      - zabbix_net
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./data/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./scripts/zabbix_dashboards:/var/lib/grafana/dashboards
      - ./configs/grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-grafana}
      - GF_AUTH_LDAP_ENABLED=${GF_AUTH_LDAP_ENABLED:-true}
      - GF_AUTH_LDAP_CONFIG_FILE=${GF_AUTH_LDAP_CONFIG_FILE:-/etc/grafana/ldap_custom.toml}
      - GF_AUTH_LDAP_ALLOW_SIGN_UP=${GF_AUTH_LDAP_ALLOW_SIGN_UP:-true}
      ##########LDAP CONFIG ENVIROMENTS##########
      - LDAP_GF_HOST=${LDAP_GF_HOST:-172.17.0.1}
      - LDAP_GF_PORT=${LDAP_GF_PORT:-389}
      - LDAP_GF_USE_SSL=${LDAP_GF_USE_SSL:-false}
      - LDAP_GF_START_TLS=${LDAP_GF_START_TLS:-false}
      - LDAP_GF_SKIP_VERIFY=${LDAP_GF_SKIP_VERIFY:-false}
      - LDAP_GF_BIND_DN=${LDAP_GF_BIND_DN:-cn=admin,dc=example,dc=org}
      - LDAP_GF_BIND_PASSWORD=${LDAP_GF_BIND_PASSWORD:-admin}
      - LDAP_GF_SEARCH_FILTER=${LDAP_GF_SEARCH_FILTER:-(cn=%s)}
      - LDAP_GF_SEARCH_BASE_DNS=${LDAP_GF_SEARCH_BASE_DNS:-dc=example,dc=org}
      - LDAP_GF_NAME=${LDAP_GF_NAME:-giveName}
      - LDAP_GF_SURNAME=${LDAP_GF_SURNAME:-sn}
      - LDAP_GF_USERNAME=${LDAP_GF_USERNAME:-cn}
      - LDAP_GF_MEMBER_OF=${LDAP_GF_MEMBER_OF:-memberOf}
      - LDAP_GF_EMAIL=${LDAP_GF_EMAIL:-email}
      - LDAP_GF_GROUP_DN_ADMIN=${LDAP_GF_GROUP_DN_ADMIN:-cn=admins,dc=example,dc=org}
      - LDAP_GF_ORG_ROLE_ADMIN=${LDAP_GF_ORG_ROLE_ADMIN:-Admin}
      - LDAP_GF_GROUP_DN_EDITOR={LDAP_GF_GROUP_DN_EDITOR:-cn=users,dc=example,dc=org}
      - LDAP_GF_ORG_ROLE_EDITOR={LDAP_GF_ORG_ROLE_EDITOR:-Editor}
      - LDAP_GF_GROUP_DN_VIEWER=${LDAP_GF_GROUP_DN_VIEWER:-*}
      - LDAP_GF_ORG_ROLE_VIEWER=${LDAP_GF_ORG_ROLE_VIEWER:-Viewer}
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  configurator:
    hostname: configuration
    build:
      dockerfile: Dockerfile.configurator
      context: ./
    command: /configurator.py ${CONFIGURATOR_OPTIONS:- }
    volumes:
      - ./scripts/configurator.py:/configurator.py:ro
      - ./configuration:/configuration:ro
      - /etc/zabbix:/etc/zabbix
      - ./data/provisioning/dashboards:/grafana/provisioning/dashboards
      - ./data/provisioning/datasources:/grafana/provisioning/datasources
      - ./scripts/zabbix_dashboards:/grafana/zabbix_dashboards
    links:
      - db
      - frontend
      - server
    extra_hosts:
      - "agent:${SUBNET_PREFIX:-172.15.0.}1"
    networks:
      zabbix_net:
        ipv4_address: ${SUBNET_PREFIX:-172.15.0.}7
    environment:
      - ZBX_SERVER_HOST=server
      - ZBX_SERVER_URL=http://frontend
      - ZBX_ADMIN_PASSWORD=${ZBX_ADMIN_PASSWORD:-zabbix}
      - ZBX_DISABLE_GUEST=${ZBX_DISABLE_GUEST:-true}
      - ZBX_AGENT_HOSTNAME=${ZBX_AGENT_HOSTNAME:-agent}
      - SMTP_SERVER=smtp.local
      - SMTP_EMAIL=${SMTP_EMAIL:-monitor@smtp.local}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS:-admin@smtp.local}
      - DEFAULT_HOST_SECRET=${DEFAULT_HOST_SECRET:- }
      - URL_LIST=${URL_LIST:- }
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
      - ZBX_CONFIG=${ZBX_CONFIG:- }
      - ZBX_ADMIN_USERS=${ZBX_ADMIN_USERS:- }
      - CONFIGURATION_FOLDER=/configuration
      - ZBX_CONFIG_FOLDER=/etc/zabbix
      - ZBX_CUSTOM_CONFIG=custom.json
      # Usage: ZBX_ADDITIONAL_TEMPLATES=template1,template2
      - ZBX_ADDITIONAL_TEMPLATES=Template Web Check, Template App Docker
      #GRAFANA ENVIRONMENTS
      - GRA_DSOURCE_YAML=/grafana/provisioning/datasources/datasource.yaml
      - GRA_DBOARD_YAML=/grafana/provisioning/dashboards/dashboard.yaml
      - GRA_ADMIN_PASS=${GF_SECURITY_ADMIN_PASSWORD}
      - GRA_PATH_TO_DASHBOARDS=/grafana/zabbix_dashboards
      - GRA_HOST=grafana
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-grafana}
networks:
  zabbix_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: ${SUBNET_PREFIX:-172.15.0.}0/24
